<a href="https://colab.research.google.com/github/SaYanZz0/100-Days-Of-ML-Code/blob/master/DataScienceTP01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 1D array ranging from 0 to 9

my_array = np.arange(10)

print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 2D array with shape (3 , 4) filled with zeros

my_2darray = np.zeros((3 , 4))
print(my_2darray)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Create array with 10 equally


my_array = np.linspace(0, 1, 10)

print(my_array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#create a matrix 3x3 with values between 0 and 1
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.96559928 0.85445254 0.19633568]
 [0.1341015  0.35278922 0.17858441]
 [0.81693604 0.10540562 0.20170666]]


In [ ]:
# array with all even integers between 10 and 50
my_integer_array = np.arange(10 , 51 , 2)
print(my_integer_array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
# Create a 5*5 identity matrix

identity_matrix = np.identity(5)

# Print the identity matrix
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Create an array with 20 logarithmically spaced values between 1 and 100

log_spaced_values = np.logspace(0, 2, 20)

# Print the array
print(log_spaced_values)

[  1.           1.27427499   1.62377674   2.06913808   2.6366509
   3.35981829   4.2813324    5.45559478   6.95192796   8.8586679
  11.28837892  14.38449888  18.32980711  23.35721469  29.76351442
  37.92690191  48.32930239  61.58482111  78.47599704 100.        ]


In [ ]:
# Array Operations

